package exception.blockFinally;

public class Main {
    //try без catch и finally - нельзя, нечего выполнять при exception
    //try только с finally - можно, при вызове exception выполнится блок finally
    //try с двумя finally - нельзя, конструкция недопустима.
}
